language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.1"
sudo: false
before_install:
  # Setup Node.js version-specific dependencies
  - "test $TRAVIS_NODE_VERSION != '0.6' -a $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
script:
  - "test $TRAVIS_NODE_VERSION != '0.6' -a $TRAVIS_NODE_VERSION != '0.8' || npm test"
  - "test $TRAVIS_NODE_VERSION  = '0.6' -o $TRAVIS_NODE_VERSION = '0.8' || npm run-script test-travis"
after_script:
  - "test $TRAVIS_NODE_VERSION != '0.6' -a $TRAVIS_NODE_VERSION != '0.8' && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
